package com.cary.cwish.pojo;

import java.math.BigDecimal;

public class Invoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Request_ID
     *
     * @mbggenerated
     */
    private Integer requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Invoice_Type
     *
     * @mbggenerated
     */
    private String invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Invoice_Sequence
     *
     * @mbggenerated
     */
    private String invoiceSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Sequence_Date
     *
     * @mbggenerated
     */
    private String sequenceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Customer_Number
     *
     * @mbggenerated
     */
    private String customerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Customer_Name
     *
     * @mbggenerated
     */
    private Object customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Customer_VatNumber
     *
     * @mbggenerated
     */
    private String customerVatnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Customer_VatAddressTele
     *
     * @mbggenerated
     */
    private String customerVataddresstele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Customer_VatBankNum
     *
     * @mbggenerated
     */
    private String customerVatbanknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.SpecialInvoice_RedNumber
     *
     * @mbggenerated
     */
    private String specialinvoiceRednumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.CommonInvoice_EquivalentCode
     *
     * @mbggenerated
     */
    private String commoninvoiceEquivalentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.CommonInvoice_EquivalentNumber
     *
     * @mbggenerated
     */
    private String commoninvoiceEquivalentnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Created_UserName
     *
     * @mbggenerated
     */
    private String createdUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Checked_UserName
     *
     * @mbggenerated
     */
    private String checkedUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Receipt_UserName
     *
     * @mbggenerated
     */
    private String receiptUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Sale_BankNum
     *
     * @mbggenerated
     */
    private String saleBanknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Sale_AddressTele
     *
     * @mbggenerated
     */
    private String saleAddresstele;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Item_Number
     *
     * @mbggenerated
     */
    private String itemNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Item_Name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Specification
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Uom_Code
     *
     * @mbggenerated
     */
    private String uomCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Qty
     *
     * @mbggenerated
     */
    private BigDecimal qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.VatInclusive_Amt
     *
     * @mbggenerated
     */
    private BigDecimal vatinclusiveAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Tax_Percent
     *
     * @mbggenerated
     */
    private BigDecimal taxPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Tax_Amt
     *
     * @mbggenerated
     */
    private BigDecimal taxAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.VatInclusive_DiscountAmt
     *
     * @mbggenerated
     */
    private BigDecimal vatinclusiveDiscountamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_VAT_EXP.Tax_DiscountAmt
     *
     * @mbggenerated
     */
    private BigDecimal taxDiscountamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.ID
     *
     * @return the value of INVOICE_VAT_EXP.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.ID
     *
     * @param id the value for INVOICE_VAT_EXP.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Request_ID
     *
     * @return the value of INVOICE_VAT_EXP.Request_ID
     *
     * @mbggenerated
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Request_ID
     *
     * @param requestId the value for INVOICE_VAT_EXP.Request_ID
     *
     * @mbggenerated
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Invoice_Type
     *
     * @return the value of INVOICE_VAT_EXP.Invoice_Type
     *
     * @mbggenerated
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Invoice_Type
     *
     * @param invoiceType the value for INVOICE_VAT_EXP.Invoice_Type
     *
     * @mbggenerated
     */
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType == null ? null : invoiceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Invoice_Sequence
     *
     * @return the value of INVOICE_VAT_EXP.Invoice_Sequence
     *
     * @mbggenerated
     */
    public String getInvoiceSequence() {
        return invoiceSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Invoice_Sequence
     *
     * @param invoiceSequence the value for INVOICE_VAT_EXP.Invoice_Sequence
     *
     * @mbggenerated
     */
    public void setInvoiceSequence(String invoiceSequence) {
        this.invoiceSequence = invoiceSequence == null ? null : invoiceSequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Sequence_Date
     *
     * @return the value of INVOICE_VAT_EXP.Sequence_Date
     *
     * @mbggenerated
     */
    public String getSequenceDate() {
        return sequenceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Sequence_Date
     *
     * @param sequenceDate the value for INVOICE_VAT_EXP.Sequence_Date
     *
     * @mbggenerated
     */
    public void setSequenceDate(String sequenceDate) {
        this.sequenceDate = sequenceDate == null ? null : sequenceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Customer_Number
     *
     * @return the value of INVOICE_VAT_EXP.Customer_Number
     *
     * @mbggenerated
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Customer_Number
     *
     * @param customerNumber the value for INVOICE_VAT_EXP.Customer_Number
     *
     * @mbggenerated
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber == null ? null : customerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Customer_Name
     *
     * @return the value of INVOICE_VAT_EXP.Customer_Name
     *
     * @mbggenerated
     */
    public Object getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Customer_Name
     *
     * @param customerName the value for INVOICE_VAT_EXP.Customer_Name
     *
     * @mbggenerated
     */
    public void setCustomerName(Object customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Customer_VatNumber
     *
     * @return the value of INVOICE_VAT_EXP.Customer_VatNumber
     *
     * @mbggenerated
     */
    public String getCustomerVatnumber() {
        return customerVatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Customer_VatNumber
     *
     * @param customerVatnumber the value for INVOICE_VAT_EXP.Customer_VatNumber
     *
     * @mbggenerated
     */
    public void setCustomerVatnumber(String customerVatnumber) {
        this.customerVatnumber = customerVatnumber == null ? null : customerVatnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Customer_VatAddressTele
     *
     * @return the value of INVOICE_VAT_EXP.Customer_VatAddressTele
     *
     * @mbggenerated
     */
    public String getCustomerVataddresstele() {
        return customerVataddresstele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Customer_VatAddressTele
     *
     * @param customerVataddresstele the value for INVOICE_VAT_EXP.Customer_VatAddressTele
     *
     * @mbggenerated
     */
    public void setCustomerVataddresstele(String customerVataddresstele) {
        this.customerVataddresstele = customerVataddresstele == null ? null : customerVataddresstele.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Customer_VatBankNum
     *
     * @return the value of INVOICE_VAT_EXP.Customer_VatBankNum
     *
     * @mbggenerated
     */
    public String getCustomerVatbanknum() {
        return customerVatbanknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Customer_VatBankNum
     *
     * @param customerVatbanknum the value for INVOICE_VAT_EXP.Customer_VatBankNum
     *
     * @mbggenerated
     */
    public void setCustomerVatbanknum(String customerVatbanknum) {
        this.customerVatbanknum = customerVatbanknum == null ? null : customerVatbanknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Comments
     *
     * @return the value of INVOICE_VAT_EXP.Comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Comments
     *
     * @param comments the value for INVOICE_VAT_EXP.Comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.SpecialInvoice_RedNumber
     *
     * @return the value of INVOICE_VAT_EXP.SpecialInvoice_RedNumber
     *
     * @mbggenerated
     */
    public String getSpecialinvoiceRednumber() {
        return specialinvoiceRednumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.SpecialInvoice_RedNumber
     *
     * @param specialinvoiceRednumber the value for INVOICE_VAT_EXP.SpecialInvoice_RedNumber
     *
     * @mbggenerated
     */
    public void setSpecialinvoiceRednumber(String specialinvoiceRednumber) {
        this.specialinvoiceRednumber = specialinvoiceRednumber == null ? null : specialinvoiceRednumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.CommonInvoice_EquivalentCode
     *
     * @return the value of INVOICE_VAT_EXP.CommonInvoice_EquivalentCode
     *
     * @mbggenerated
     */
    public String getCommoninvoiceEquivalentcode() {
        return commoninvoiceEquivalentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.CommonInvoice_EquivalentCode
     *
     * @param commoninvoiceEquivalentcode the value for INVOICE_VAT_EXP.CommonInvoice_EquivalentCode
     *
     * @mbggenerated
     */
    public void setCommoninvoiceEquivalentcode(String commoninvoiceEquivalentcode) {
        this.commoninvoiceEquivalentcode = commoninvoiceEquivalentcode == null ? null : commoninvoiceEquivalentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.CommonInvoice_EquivalentNumber
     *
     * @return the value of INVOICE_VAT_EXP.CommonInvoice_EquivalentNumber
     *
     * @mbggenerated
     */
    public String getCommoninvoiceEquivalentnumber() {
        return commoninvoiceEquivalentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.CommonInvoice_EquivalentNumber
     *
     * @param commoninvoiceEquivalentnumber the value for INVOICE_VAT_EXP.CommonInvoice_EquivalentNumber
     *
     * @mbggenerated
     */
    public void setCommoninvoiceEquivalentnumber(String commoninvoiceEquivalentnumber) {
        this.commoninvoiceEquivalentnumber = commoninvoiceEquivalentnumber == null ? null : commoninvoiceEquivalentnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Created_UserName
     *
     * @return the value of INVOICE_VAT_EXP.Created_UserName
     *
     * @mbggenerated
     */
    public String getCreatedUsername() {
        return createdUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Created_UserName
     *
     * @param createdUsername the value for INVOICE_VAT_EXP.Created_UserName
     *
     * @mbggenerated
     */
    public void setCreatedUsername(String createdUsername) {
        this.createdUsername = createdUsername == null ? null : createdUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Checked_UserName
     *
     * @return the value of INVOICE_VAT_EXP.Checked_UserName
     *
     * @mbggenerated
     */
    public String getCheckedUsername() {
        return checkedUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Checked_UserName
     *
     * @param checkedUsername the value for INVOICE_VAT_EXP.Checked_UserName
     *
     * @mbggenerated
     */
    public void setCheckedUsername(String checkedUsername) {
        this.checkedUsername = checkedUsername == null ? null : checkedUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Receipt_UserName
     *
     * @return the value of INVOICE_VAT_EXP.Receipt_UserName
     *
     * @mbggenerated
     */
    public String getReceiptUsername() {
        return receiptUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Receipt_UserName
     *
     * @param receiptUsername the value for INVOICE_VAT_EXP.Receipt_UserName
     *
     * @mbggenerated
     */
    public void setReceiptUsername(String receiptUsername) {
        this.receiptUsername = receiptUsername == null ? null : receiptUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Sale_BankNum
     *
     * @return the value of INVOICE_VAT_EXP.Sale_BankNum
     *
     * @mbggenerated
     */
    public String getSaleBanknum() {
        return saleBanknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Sale_BankNum
     *
     * @param saleBanknum the value for INVOICE_VAT_EXP.Sale_BankNum
     *
     * @mbggenerated
     */
    public void setSaleBanknum(String saleBanknum) {
        this.saleBanknum = saleBanknum == null ? null : saleBanknum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Sale_AddressTele
     *
     * @return the value of INVOICE_VAT_EXP.Sale_AddressTele
     *
     * @mbggenerated
     */
    public String getSaleAddresstele() {
        return saleAddresstele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Sale_AddressTele
     *
     * @param saleAddresstele the value for INVOICE_VAT_EXP.Sale_AddressTele
     *
     * @mbggenerated
     */
    public void setSaleAddresstele(String saleAddresstele) {
        this.saleAddresstele = saleAddresstele == null ? null : saleAddresstele.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Item_Number
     *
     * @return the value of INVOICE_VAT_EXP.Item_Number
     *
     * @mbggenerated
     */
    public String getItemNumber() {
        return itemNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Item_Number
     *
     * @param itemNumber the value for INVOICE_VAT_EXP.Item_Number
     *
     * @mbggenerated
     */
    public void setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber == null ? null : itemNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Item_Name
     *
     * @return the value of INVOICE_VAT_EXP.Item_Name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Item_Name
     *
     * @param itemName the value for INVOICE_VAT_EXP.Item_Name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Specification
     *
     * @return the value of INVOICE_VAT_EXP.Specification
     *
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Specification
     *
     * @param specification the value for INVOICE_VAT_EXP.Specification
     *
     * @mbggenerated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Uom_Code
     *
     * @return the value of INVOICE_VAT_EXP.Uom_Code
     *
     * @mbggenerated
     */
    public String getUomCode() {
        return uomCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Uom_Code
     *
     * @param uomCode the value for INVOICE_VAT_EXP.Uom_Code
     *
     * @mbggenerated
     */
    public void setUomCode(String uomCode) {
        this.uomCode = uomCode == null ? null : uomCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Qty
     *
     * @return the value of INVOICE_VAT_EXP.Qty
     *
     * @mbggenerated
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Qty
     *
     * @param qty the value for INVOICE_VAT_EXP.Qty
     *
     * @mbggenerated
     */
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.VatInclusive_Amt
     *
     * @return the value of INVOICE_VAT_EXP.VatInclusive_Amt
     *
     * @mbggenerated
     */
    public BigDecimal getVatinclusiveAmt() {
        return vatinclusiveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.VatInclusive_Amt
     *
     * @param vatinclusiveAmt the value for INVOICE_VAT_EXP.VatInclusive_Amt
     *
     * @mbggenerated
     */
    public void setVatinclusiveAmt(BigDecimal vatinclusiveAmt) {
        this.vatinclusiveAmt = vatinclusiveAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Tax_Percent
     *
     * @return the value of INVOICE_VAT_EXP.Tax_Percent
     *
     * @mbggenerated
     */
    public BigDecimal getTaxPercent() {
        return taxPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Tax_Percent
     *
     * @param taxPercent the value for INVOICE_VAT_EXP.Tax_Percent
     *
     * @mbggenerated
     */
    public void setTaxPercent(BigDecimal taxPercent) {
        this.taxPercent = taxPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Tax_Amt
     *
     * @return the value of INVOICE_VAT_EXP.Tax_Amt
     *
     * @mbggenerated
     */
    public BigDecimal getTaxAmt() {
        return taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Tax_Amt
     *
     * @param taxAmt the value for INVOICE_VAT_EXP.Tax_Amt
     *
     * @mbggenerated
     */
    public void setTaxAmt(BigDecimal taxAmt) {
        this.taxAmt = taxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.VatInclusive_DiscountAmt
     *
     * @return the value of INVOICE_VAT_EXP.VatInclusive_DiscountAmt
     *
     * @mbggenerated
     */
    public BigDecimal getVatinclusiveDiscountamt() {
        return vatinclusiveDiscountamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.VatInclusive_DiscountAmt
     *
     * @param vatinclusiveDiscountamt the value for INVOICE_VAT_EXP.VatInclusive_DiscountAmt
     *
     * @mbggenerated
     */
    public void setVatinclusiveDiscountamt(BigDecimal vatinclusiveDiscountamt) {
        this.vatinclusiveDiscountamt = vatinclusiveDiscountamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_VAT_EXP.Tax_DiscountAmt
     *
     * @return the value of INVOICE_VAT_EXP.Tax_DiscountAmt
     *
     * @mbggenerated
     */
    public BigDecimal getTaxDiscountamt() {
        return taxDiscountamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_VAT_EXP.Tax_DiscountAmt
     *
     * @param taxDiscountamt the value for INVOICE_VAT_EXP.Tax_DiscountAmt
     *
     * @mbggenerated
     */
    public void setTaxDiscountamt(BigDecimal taxDiscountamt) {
        this.taxDiscountamt = taxDiscountamt;
    }
}