package com.cary.cwish.dao;

import com.cary.cwish.pojo.Invoice;

public interface InvoiceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    Invoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Invoice record);
}