package com.cary.cwish.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cary.cwish.pojo.Invoice;

public interface InvoiceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    Invoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOICE_VAT_EXP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Invoice record);
    
    /**
     * This method is used to get a number of records of INVOICE_VAT_EXP
     */
    List<Invoice> selectHundredRecords(@Param("startNum")Integer startNum, @Param("requiredId")Integer requiredId);
    
    /**
     * This method is to get count of whole group
     */
    int selectCountRecords(@Param("requiredId")Integer requiredId);
    
    /**
     * This method is to get list invoices by request id
     */
    List<Invoice> selectRecordsByRequiredId(@Param("requiredId")Integer requiredId);
}